# Generated by Django 5.1.1 on 2024-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "order_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "order_details",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delete_date", models.DateField(default=None, null=True)),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
    ]
